TASK-1723 마이크로비트 활동 VF
team-monolith-product/pxt pull request #2
Opened 2024-07-09 10:00 UTC by paulkim3151

2024-07-10 05:14 UTC, paulkim3151 commented on webapp/src/app.tsx
> +        case "cloudheader":
cloudheader hash값이 있는 url에서 home을 열지 않게 만드는 설정입니다.

2024-07-10 05:15 UTC, paulkim3151 commented on webapp/src/auth.ts
> +        return { id: "00000000-0000-0000-0000-000000000000" };
이렇게 userId를 아무 값이나 설정해서 프로젝트의 소요자 id에 관한 체크를 무력화했습니다.

2024-07-11 23:33 UTC, a3626a requested changes

2024-07-11 23:33 UTC, a3626a commented on pxtlib/auth.ts
> +            url = `${Cloud.apiRoot.replace(/\/$/, "")}${url}`;
마지막에 /를 지우는 replace인가요?

2024-07-11 23:33 UTC, a3626a commented on pxtlib/codle/cookie.ts
> +      )
이해가 너무 힘든 코드네요... 주석이라고 조금 있으면 좋겠습니다

name을 쿠키에 적합한 포맷으로 이스케이프(인코딩)하는 것 같아 보이는데 혹시 더 이해하기 쉬운 이름의 네이티브 함수는 없을까요?

2024-07-11 23:33 UTC, a3626a commented on pxtlib/codle/cookie.ts
> +    return `${name}_${tenant}_${getEnv()}`;
테넌트 가져오는 코드가 없지 않나요?

2024-07-11 23:33 UTC, a3626a commented on webapp/src/app.tsx
> +    /*
불필요한 주석

2024-07-11 23:33 UTC, a3626a commented on webapp/src/auth.ts
> +        return { id: "00000000-0000-0000-0000-000000000000" };
이러면 무력화가 되나요? 프로젝트 소유자도 항상 0000을 주도록 하구요?

2024-07-11 23:56 UTC, paulkim3151 commented on webapp/src/auth.ts
> +        return { id: "00000000-0000-0000-0000-000000000000" };
네 기본 프로젝트 생성시 headr.cloudUserId 값을 이 값으로 주고, 클라이언트는 모든 userId를 이 값으로 주어서 사실상 모든 프로젝트가 동일한 유저의 것으로 생성되게 한 로직입니다.

2024-07-11 23:57 UTC, paulkim3151 commented on pxtlib/auth.ts
> +            url = `${Cloud.apiRoot.replace(/\/$/, "")}${url}`;
넵 이게 어느곳에서는 뒤에 붙는 path가 `/` 으로 시작할때도 있고, 시작 안할때도 있더라고요.

2024-07-11 23:59 UTC, paulkim3151 commented on pxtlib/codle/cookie.ts
> +      )
일단 chatGPT가 제안해준 코드이긴합니다. 외부 라이브러리를 쓰지 않고 쿠키 가져오는 코드를 물어봤는데 이렇게 줬습니다. 주석 달아놓겠습니다.

2024-07-11 23:59 UTC, paulkim3151 commented on pxtlib/codle/cookie.ts
> +    return `${name}_${tenant}_${getEnv()}`;
질문의 의미를 잘 모르겠습니다. 코드가 잘못되었다는 의미인가요?

2024-07-12 00:01 UTC, paulkim3151 commented on webapp/src/app.tsx
> +    /*
기존 코드를 남겨놓는다는 생각으로 주석처리를 하긴 했는데, 다 지워버리는 것이 좋을까요?

2024-07-12 01:33 UTC, a3626a commented on webapp/src/auth.ts
> +        return { id: "00000000-0000-0000-0000-000000000000" };
이게 다르면 동작이 어떻게 되나요? 혹시 이 처리가 보안 관점에서 문제될 수는 없을까요?

2024-07-12 01:33 UTC, a3626a commented on pxtlib/codle/cookie.ts
> +    return `${name}_${tenant}_${getEnv()}`;
아 아닙니다. 이해했습니다.

2024-07-12 01:34 UTC, a3626a commented on webapp/src/app.tsx
> +    /*
아뇨 `/*` 로도 주석을 하시고 `//`로도 주석을 하셔서요.

2024-07-12 01:34 UTC, a3626a commented on webapp/src/app.tsx
> +    /*
아 이거 좀 깃허브가 이상하네요..
![image](https://github.com/user-attachments/assets/65f0d1df-3361-4f19-b8d6-6572cd7aa8b6)

전 원래 코드도 주석처리 된 것으로 이해했어요.

2024-07-12 01:36 UTC, a3626a commented on pxtlib/codle/cookie.ts
> +      )
저 replace가 escape 로직인데요. 혹시 url encode 처럼 더 적합한 함수가 없을까요? replace 쓰지 말구요.

2024-07-12 01:56 UTC, paulkim3151 commented on webapp/src/app.tsx
> +    /*
원래 코드를 주석처리한 것이 맞습니다. 원래 코드 동작을 삭제하였지만, 코드는 남겨놓으려는 목적으로 주석처리했습니다.

2024-07-12 01:58 UTC, a3626a commented on webapp/src/app.tsx
> +    /*
제가 보기에는 변경 전 코드도 이미 주석 처리 되어 있는 것처럼 회색으로 나왔어요. 원본 코드도 주석된 것처럼. 그래서 제가 혼동한 것이고, 문제 없습니다.

2024-07-12 08:33 UTC, a3626a commented
여긴 소유자 처리 결정하고 다시 리뷰주세요.

2024-07-15 05:21 UTC, paulkim3151 commented on webapp/src/auth.ts
> +        return { id: "00000000-0000-0000-0000-000000000000" };
API 단에서 권한 설정이 되어서 프론트의 userId 값은 0000... 으로 두어도 충분할 것 같습니다.
도리어 코들의 userId 값을 설정하면 의도치 않은 sideEffect가 생길 수 있다고 판단했습니다.

2024-07-15 05:23 UTC, paulkim3151 commented on pxtlib/codle/cookie.ts
> +      )
수정했습니다. 말씀하신 escape 로직은 여기에서는 없어도 될것 같습니다.

2024-07-15 05:25 UTC, paulkim3151 commented
반영했습니다.

2024-07-15 08:38 UTC, a3626a approved these changes

2024-07-15 08:40 UTC, merged